/* tslint:disable */
/* eslint-disable */
/**
 * Jupiter API
 * Jupiter quote and swap API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponseDefaultMarketInfos,
    InlineResponseDefaultMarketInfosFromJSON,
    InlineResponseDefaultMarketInfosFromJSONTyped,
    InlineResponseDefaultMarketInfosToJSON,
} from './InlineResponseDefaultMarketInfos';

/**
 * Data from /v1/quote
 * @export
 * @interface V1SwapRoute
 */
export interface V1SwapRoute {
    /**
     * 
     * @type {number}
     * @memberof V1SwapRoute
     */
    inAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof V1SwapRoute
     */
    outAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof V1SwapRoute
     */
    outAmountWithSlippage?: number;
    /**
     * 
     * @type {number}
     * @memberof V1SwapRoute
     */
    priceImpactPct?: number;
    /**
     * 
     * @type {Array<InlineResponseDefaultMarketInfos>}
     * @memberof V1SwapRoute
     */
    marketInfos?: Array<InlineResponseDefaultMarketInfos>;
}

export function V1SwapRouteFromJSON(json: any): V1SwapRoute {
    return V1SwapRouteFromJSONTyped(json, false);
}

export function V1SwapRouteFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1SwapRoute {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'inAmount': !exists(json, 'inAmount') ? undefined : json['inAmount'],
        'outAmount': !exists(json, 'outAmount') ? undefined : json['outAmount'],
        'outAmountWithSlippage': !exists(json, 'outAmountWithSlippage') ? undefined : json['outAmountWithSlippage'],
        'priceImpactPct': !exists(json, 'priceImpactPct') ? undefined : json['priceImpactPct'],
        'marketInfos': !exists(json, 'marketInfos') ? undefined : ((json['marketInfos'] as Array<any>).map(InlineResponseDefaultMarketInfosFromJSON)),
    };
}

export function V1SwapRouteToJSON(value?: V1SwapRoute | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'inAmount': value.inAmount,
        'outAmount': value.outAmount,
        'outAmountWithSlippage': value.outAmountWithSlippage,
        'priceImpactPct': value.priceImpactPct,
        'marketInfos': value.marketInfos === undefined ? undefined : ((value.marketInfos as Array<any>).map(InlineResponseDefaultMarketInfosToJSON)),
    };
}

